### PR TITLE
Upstream sync 05-07-23

### PR DESCRIPTION
**Pull request by fedepaol**
Synching with upstream

### CODE REVIEW

**Comment by liornoy** [comment]
maybe let's not merge the networkUnavailable condition feature now, and I'll deal with this on my own later?

**Comment by fedepaol** [comment]
> maybe let's not merge the networkUnavailable condition feature now, and I'll deal with this on my own later?

Yep, I have the feeling that that field is not even set in ocp (or at least it wasn't in 4.13).

**Comment by liornoy** [comment]
I think we missed this commit: Escape curly braces in format string 1284a44ecb2e6bdb606285907d6d2d72008834ce
I can add this together with the network unavailable PR if you want.

**Comment by liornoy** [comment]
Plus all the dependabot commits are missing

**Comment by fedepaol** [comment]
> Plus all the dependabot commits are missing

I aligned manually the go.mod / go.sum files in the last commit.

**Comment by fedepaol** [comment]
> I think we missed this commit: Escape curly braces in format string [1284a44](https://github.com/openshift/metallb/commit/1284a44ecb2e6bdb606285907d6d2d72008834ce) I can add this together with the network unavailable PR if you want.

Yes please, let's get this through

**Pull request merged**
