### PR TITLE
Sync with upstream MetalLB

### PR DESCRIPTION
**Pull request by sabinaaledort**

### CODE REVIEW

**Comment by cgoncalves** [comment]
It looks like PROVISIONING_HOST_EXTERNAL_IPV4 and PROVISIONING_HOST_EXTERNAL_IPV6 may need to be set.
There were also two L2 metric tests that failed with "no interface found in 192.168.10.0 network".

**Comment by sabinaaledort** [comment]
> It looks like PROVISIONING_HOST_EXTERNAL_IPV4 and PROVISIONING_HOST_EXTERNAL_IPV6 may need to be set. There were also two L2 metric tests that failed with "no interface found in 192.168.10.0 network".

yes, that's a bug in the dev-scripts, im fixing it. another issue is that we exepect both ipv4 and ipv6 in the tests.

**Comment by sabinaaledort** [comment]
will be retested after merging:
https://github.com/openshift-metal3/dev-scripts/pull/1314
https://github.com/openshift/release/pull/23991

**Comment by sabinaaledort** [comment]
the configuration is working.
10 tests passed and 5 failed

**Pull request merged**
