### PR TITLE
OCPBUGS-18838: Backport liveness to 4.12

### PR DESCRIPTION
**Pull request by oribon**
clean cherry-pick from 4.13 of the relevant commits

### CODE REVIEW

**Comment by fedepaol** [comment]
We might need the corresponding part on the operator, where we effectively deploy the new version of the manifests.

**Comment by oribon** [comment]
> We might need the corresponding part on the operator, where we effectively deploy the new version of the manifests.

filed https://github.com/openshift/metallb-operator/pull/187

**Comment by andreaskaris** [comment]
@oribon @asood-rh This here needs to be QE tested and needs a cherry-pick approved. Can you prioritize this as I've got a customer waiting for this. Thanks!  (needs to be tested with https://github.com/openshift/metallb-operator/pull/187 and go in before, then https://github.com/openshift/metallb-operator/pull/187 can go in as far as I understand)

**Pull request merged**
