### PR TITLE
Syncmetallb031024

### PR DESCRIPTION
**Pull request by karampok**
Sync to the upstream

### CODE REVIEW

**Comment by karampok** [comment]
@fedepaol AFAIU
1. the old ipi-ovn test are green just the job is not finishing
```
72/72 test passed

[36mINFO[0m[2024-10-04T13:10:26Z] Ran for 4h5m39s                              
[31mERRO[0m[2024-10-04T13:10:26Z] Some steps failed:                           
[31mERRO[0m[2024-10-04T13:10:26Z] 
  * could not run steps: execution cancelled 
[36mINFO[0m[2024-10-04T13:10:26Z] Reporting job state 'failed' with reason 'executing_graph:interrupted' 
{"component":"entrypoint","file":"sigs.k8s.io/prow/pkg/entrypoint/run.go:264","func":"sigs.k8s.io/prow/pkg/entrypoint.gracefullyTerminate","level":"error","msg":"Process gracefully exited before 1h0m0s grace period","severity":"error","time":"2024-10-04T13:10:26Z"}
```
2. The frrk8s-cno fails, should I retry, debug, overwrite? what do you think?
Thanks

**Comment by karampok** [comment]
@fedepaol  the frrk8s-cno fails, should we overwrite? or try to fix it? Thanks

**Comment by fedepaol** [comment]
> @fedepaol the frrk8s-cno fails, should we overwrite? or try to fix it? Thanks

is it failing because of frrk8s + cno?

**Pull request merged**
