### PR TITLE
OCPBUGS-4845: MetallB ignores NodeNetworkUnavailable condition

### PR DESCRIPTION
**Pull request by liornoy**
This PR syncs with u/s metallb and brings the NodeNetworkUnavailable condition bug fix.

### CODE REVIEW

**Comment by liornoy** [comment]
Let's hold this until we have this: https://github.com/metallb/metallb/pull/1906

**Comment by liornoy** [comment]
Added a wip commit, trying to fix the test's failures

**Comment by fedepaol** [comment]
Can you align with all we have upstream?
Also, use what we did in https://github.com/metallb/metallb/pull/1899 to use the openshift frr version in e2e

**Comment by fedepaol** [comment]
> sure

hopefully the bfd echo bug should be fixed by that

**Comment by liornoy** [comment]
Closed in favor of: https://github.com/openshift/metallb/pull/119

**Pull request closed without merging**
